project_id = "ssznmzijopyxkwpctcxw"

[functions.auth-email-hook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.process-bostta-delivery]
verify_jwt = true

[functions.department-monthly-budget]
verify_jwt = true

[functions.zodex-bill-details]
verify_jwt = true

[functions.zodex-probe]
verify_jwt = true

[functions.sync-zodex-deliveries]
verify_jwt = true

[functions.sync-zodex-shipments]
verify_jwt = true
