// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/list-orders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-orders.ts
var list_orders_default = defineTool({
  name: "list_orders",
  title: "List orders",
  description: "List recent orders (order number, status, totals, dates). Optionally filter by status, moderator, or a created_at date range.",
  inputSchema: {
    status: z.string().optional().describe("Order status filter, e.g. pending, delivered, cancelled."),
    moderator: z.string().optional().describe("Moderator name filter (exact match)."),
    date_from: z.string().optional().describe("ISO date (YYYY-MM-DD) lower bound on created_at."),
    date_to: z.string().optional().describe("ISO date (YYYY-MM-DD) upper bound on created_at."),
    limit: z.number().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, moderator, date_from, date_to, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select(
      "order_number, status, payment_status, total, subtotal, delivery_fee, moderator, fulfillment_type, shipping_company, created_at, delivered_at"
    ).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (status) q = q.eq("status", status);
    if (moderator) q = q.eq("moderator", moderator);
    if (date_from) q = q.gte("created_at", `${date_from}T00:00:00Z`);
    if (date_to) q = q.lte("created_at", `${date_to}T23:59:59Z`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_order_default = defineTool2({
  name: "get_order",
  title: "Get order details",
  description: "Get one order by its order number, including its line items (product, quantity, prices).",
  inputSchema: {
    order_number: z2.string().trim().describe("The order number, e.g. ORD-20260904-303259.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select(
      "id, order_number, status, payment_status, payment_method, subtotal, discount, delivery_fee, total, moderator, fulfillment_type, shipping_company, shipping_bill_no, notes, created_at, delivered_at"
    ).eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order)
      return { content: [{ type: "text", text: `No order found with number ${order_number}` }], isError: true };
    const { data: items } = await supabase.from("order_items").select("product_name, quantity, unit_price, total_price, offer_name").eq("order_id", order.id);
    const result = { ...order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { order: result }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z3 } from "npm:zod@^3.25.76";
function num(v) {
  const x = Number(v);
  return Number.isFinite(x) ? x : 0;
}
var sales_summary_default = defineTool3({
  name: "sales_summary",
  title: "Sales summary",
  description: "Aggregated sales summary for a date range: order counts by status, total sales, average order value, and top moderators.",
  inputSchema: {
    date_from: z3.string().describe("Start date (YYYY-MM-DD)."),
    date_to: z3.string().describe("End date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("status, total, moderator").gte("created_at", `${date_from}T00:00:00Z`).lte("created_at", `${date_to}T23:59:59Z`).limit(5e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const valid = rows.filter((r) => r.status !== "cancelled");
    const totalSales = valid.reduce((s, r) => s + num(r.total), 0);
    const byStatus = {};
    for (const r of rows) byStatus[r.status] = (byStatus[r.status] ?? 0) + 1;
    const byMod = /* @__PURE__ */ new Map();
    for (const r of valid) {
      const key = r.moderator || "\u063A\u064A\u0631 \u0645\u062D\u062F\u062F";
      const cur = byMod.get(key) ?? { orders: 0, total: 0 };
      cur.orders += 1;
      cur.total += num(r.total);
      byMod.set(key, cur);
    }
    const summary = {
      range: { from: date_from, to: date_to },
      orders_count: rows.length,
      valid_orders: valid.length,
      cancelled_orders: rows.length - valid.length,
      total_sales: Number(totalSales.toFixed(2)),
      avg_order_value: valid.length ? Number((totalSales / valid.length).toFixed(2)) : 0,
      by_status: byStatus,
      top_moderators: Array.from(byMod.entries()).sort((a, b) => b[1].total - a[1].total).slice(0, 10).map(([moderator, v]) => ({ moderator, orders: v.orders, total: Number(v.total.toFixed(2)) }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_products_default = defineTool4({
  name: "list_products",
  title: "List products",
  description: "\u0642\u0627\u0626\u0645\u0629 \u0627\u0644\u0645\u0646\u062A\u062C\u0627\u062A \u0628\u0623\u0633\u0645\u0627\u0626\u0647\u0627 \u0648\u0641\u0626\u0627\u062A\u0647\u0627 \u0648\u0633\u0639\u0631 \u0627\u0644\u0628\u064A\u0639 \u0648\u0648\u062D\u062F\u0629 \u0627\u0644\u0642\u064A\u0627\u0633. \u062A\u062D\u0630\u064A\u0631: \u062D\u0642\u0644 stock \u0647\u0646\u0627 \u062D\u0642\u0644 \u062A\u062C\u0645\u064A\u0639\u064A \u0642\u062F\u064A\u0645 \u0639\u0644\u0649 \u0645\u0633\u062A\u0648\u0649 \u0627\u0644\u0645\u0646\u062A\u062C \u0648\u0644\u0627 \u064A\u0645\u062B\u0644 \u0631\u0635\u064A\u062F \u0645\u062E\u0632\u0646 \u0645\u062D\u062F\u062F \u2014 \u0644\u0623\u0631\u0635\u062F\u0629 \u0627\u0644\u0645\u062E\u0627\u0632\u0646 (\u0641\u0639\u0644\u064A/\u0645\u062D\u062C\u0648\u0632/\u0645\u062A\u0627\u062D) \u0627\u0633\u062A\u062E\u062F\u0645 \u0623\u062F\u0627\u0629 inventory_balances.",
  inputSchema: {
    search: z4.string().optional().describe("\u0628\u062D\u062B \u062C\u0632\u0626\u064A \u0641\u064A \u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u062A\u062C."),
    category: z4.string().optional().describe("\u062A\u0635\u0641\u064A\u0629 \u0628\u0627\u0644\u0641\u0626\u0629."),
    active_only: z4.boolean().optional().describe("\u0627\u0644\u0645\u0646\u062A\u062C\u0627\u062A \u0627\u0644\u0646\u0634\u0637\u0629 \u0641\u0642\u0637."),
    page: z4.number().optional().describe("\u0631\u0642\u0645 \u0627\u0644\u0635\u0641\u062D\u0629 \u064A\u0628\u062F\u0623 \u0645\u0646 1."),
    page_size: z4.number().optional().describe("\u062D\u062C\u0645 \u0627\u0644\u0635\u0641\u062D\u0629 (\u0627\u0641\u062A\u0631\u0627\u0636\u064A 50\u060C \u0623\u0642\u0635\u0649 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, active_only, page, page_size }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const size = Math.min(Math.max(page_size ?? 50, 1), 200);
    const pg = Math.max(page ?? 1, 1);
    const from = (pg - 1) * size;
    let q = supabase.from("products").select("id, name, category, price, unit, stock, is_active", { count: "exact" }).order("name", { ascending: true });
    if (search) q = q.ilike("name", `%${search}%`);
    if (category) q = q.eq("category", category);
    if (active_only) q = q.eq("is_active", true);
    const { data, error, count } = await q.range(from, from + size - 1);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = {
      total_count: count ?? 0,
      page: pg,
      page_size: size,
      returned: (data ?? []).length,
      has_more: from + (data ?? []).length < (count ?? 0),
      currency: "EGP",
      stock_field_note: "products.stock \u062D\u0642\u0644 \u0642\u062F\u064A\u0645 \u0639\u0644\u0649 \u0645\u0633\u062A\u0648\u0649 \u0627\u0644\u0645\u0646\u062A\u062C (\u0644\u064A\u0633 \u0631\u0635\u064A\u062F \u0645\u062E\u0632\u0646). \u0627\u0633\u062A\u062E\u062F\u0645 inventory_balances \u0644\u0644\u0631\u0635\u064A\u062F \u0627\u0644\u0641\u0639\u0644\u064A \u0648\u0627\u0644\u0645\u062D\u062C\u0648\u0632 \u0648\u0627\u0644\u0645\u062A\u0627\u062D \u0644\u0643\u0644 \u0645\u062E\u0632\u0646 \u0648\u0648\u062D\u062F\u0629.",
      products: data ?? []
    };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ssznmzijopyxkwpctcxw";
var mcp_default = defineMcp({
  name: "naam-al-asima-management-system",
  title: "Naam Al-Asima Management System",
  version: "0.1.0",
  instructions: "Read-only tools for the Naam Al-Asima (Capital Ostrich) management system. Use `list_orders` and `get_order` for order data, `sales_summary` for aggregated sales over a date range, and `list_products` for products, prices and stock. All data access runs as the signed-in user with their own permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_orders_default, get_order_default, sales_summary_default, list_products_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
